name: Send Feedback Email

on:
  repository_dispatch:
    types: [feedback]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send feedback email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Mobilní Kuchařka] ${{ github.event.client_payload.type }}: ${{ github.event.client_payload.title }}"
          to: devzoufaly@gmail.com
          from: Mobilní Kuchařka <${{ secrets.MAIL_USERNAME }}>
          reply_to: ${{ github.event.client_payload.userEmail }}
          body: |
            Typ: ${{ github.event.client_payload.type }}
            Verze aplikace: ${{ github.event.client_payload.appVersion }}
            Jazyk aplikace: ${{ github.event.client_payload.language }}
            E-mail uživatele: ${{ github.event.client_payload.userEmail }}

            Název/nadpis: ${{ github.event.client_payload.title }}

            Popis:
            ${{ github.event.client_payload.description }}

            Jak zopakovat:
            ${{ github.event.client_payload.reproSteps }}
